// Stable package entrypoint.
// Native loader is generated by @napi-rs/cli as `nrql.js`.
/* eslint-disable */
// @ts-nocheck

let binding = null
const loadErrors = []

try {
  binding = require('./nrql.js')
} catch (err) {
  loadErrors.push(err)
}

if (!binding) {
  try {
    binding = require('./nrql-js.wasm32-unknown-unknown.cjs')
  } catch (err) {
    loadErrors.push(err)
  }
}

if (!binding) {
  try {
    binding = require('@nrql-js/nrql-wasm32-unknown-unknown')
  } catch (err) {
    loadErrors.push(err)
  }
}

if (!binding) {
  if (loadErrors.length > 0) {
    throw new Error('Failed to load nrql bindings from generated/wasm fallback paths', {
      cause: loadErrors.reduce((prev, cur) => {
        cur.cause = prev
        return cur
      }),
    })
  }
  throw new Error('Failed to load nrql bindings')
}

module.exports = binding
module.exports.ComparisonOp = binding.ComparisonOp
module.exports.OrderDirection = binding.OrderDirection
module.exports.parseNrql = binding.parseNrql
module.exports.SelectArgKind = binding.SelectArgKind
module.exports.TimeUnit = binding.TimeUnit
